# Generated by Django 5.1rc1 on 2024-09-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
